name: frosty_float_navigation
description: A sleek frosted glass-style floating bottom navigation bar for Flutter apps.
version: 1.0.0
homepage: https://github.com/kinleyrabgay/frosty_float_navigation
repository: https://github.com/kinleyrabgay/frosty_float_navigation
issue_tracker: https://github.com/kinleyrabgay/frosty_float_navigation/issues

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0